### PR TITLE
fix tests to be reproducible

### PR DESCRIPTION
**Pull request by bhearsum**
This is basically a subset of https://github.com/mozilla/libdmg-hfsplus/pull/10, with my comments addressed. @vasi - I've made you a co-author on it seeing as what I've kept is ~90% yours. If you'd prefer, you could incorporate the changes here into #10 to keep clearer credit for this.

### CODE REVIEW

**Comment by bhearsum** [comment]
@vasi - If you have time, I'd also love to see if these tests now pass for you locally (noting that only the reference ones are expected to succeed on macOS).

**Comment by vasi** [comment]
Since we last talked:

* I upgraded my laptop to Ubuntu 24.04, and now all non-reference tests seem to pass if I run them one at a time! I've not been able to reproduce failures even in a 22.04 Docker container, so I'm left unable to debug.
* I changed my PR at #10 to just add Github CI for this repo. It seems to pass, and should be reproducible, which accomplishes most of what I want.
* This PR seems worthwhile too! It _does_ pass for me locally on a clean clone--unfortunately it's a bit too easy to accidentally leave junk in my clone.

**Comment by vasi** [comment]
Oh boy, and looks like you _also_ added Github Actions lol.

**Comment by vasi** [comment]
Ok so my proposal for where to go from here:
* LGTM
* I'll close #10 now, since it seems redundant
* I'm gonna work on a way to run tests locally in a more reproducible way
* I'll rebase #9  on the mozilla branch once this is merged

**Comment by bhearsum** [comment]
Sounds good to me! Sorry for any confusion I caused!

**Review by ncalexan — APPROVED** [review]
Amazing!  I'm thrilled to see this get better.

**Pull request merged**
